from zoom_ingest.zoom_shared.zoom_dataclasses import (
    CDR,
    PersonaDetails,
    Recording,
    Transcript,
    ZoomDTO,
    ZoomEntity,
)

mocked_list_calls_logs = [
    {
        "id": "cf27f361-606d-46d2-be78-0367727636b0",
        "user_id": "XD5VZiZVTMCrBnaw7Dw0iw",
        "call_type": "voip",
        "caller_number": "+442033704156",
        "caller_number_type": 2,
        "caller_number_source": "internal",
        "caller_location": "London",
        "callee_number": "800",
        "callee_number_type": 1,
        "callee_name": "foo Asset Management (UK) Ltd",
        "direction": "inbound",
        "duration": 18,
        "result": "Auto Recorded",
        "date_time": "2022-09-16T17:25:17Z",
        "path": "sharedLines",
        "recording_id": "cf27f361606d46d2be780367727636b0",
        "recording_type": "Automatic",
        "has_voicemail": False,
        "call_id": "7144030050769469138",
        "owner": {
            "type": "user",
            "id": "XD5VZiZVTMCrBnaw7Dw0iw",
            "name": "foo Asset Management (UK) Ltd",
            "extension_number": 800,
        },
        "caller_country_code": "44",
        "caller_country_iso_code": "GB",
        "callee_did_number": "+442038264491",
        "callee_country_code": "44",
        "callee_country_iso_code": "GB",
        "answer_start_time": "2022-09-16T17:25:36Z",
        "call_end_time": "2022-09-16T17:25:54Z",
        "department": "Business Management",
        "cost_center": "",
    },
]

mocked_list_calls_logs_empty = []

mocked_download_call_transcript = {
    "type": "zoom_transcript",
    "ver": 1,
    "recording_id": "cf27f361606d46d2be780367727636b0",
    "meeting_id": "cf27f361606d46d2be780367727636b0",
    "account_id": "23vOATmyRHmTaj4vhE2Usg",
    "host_id": "AAWHrAgwRs6x4m6ImhNiew",
    "recording_start": "2022-09-16T17:25:36Z",
    "recording_end": "2022-09-16T17:25:53Z",
    "timeline": [
        {
            "text": "Bakery test management.",
            "end_ts": "00:00:02.679",
            "ts": "00:00:00.700",
            "users": [
                {
                    "username": "foo Asset Management UK Ltd",
                    "multiple_people": False,
                    "user_id": "85180477870493817096",
                    "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                    "client_type": 0,
                },
            ],
        },
        {
            "text": "You have a good personal trainer to see Simon S. Lima,",
            "end_ts": "00:00:06.580",
            "ts": "00:00:03.230",
            "users": [
                {
                    "username": "442033704156",
                    "multiple_people": False,
                    "multiple_people": False,
                    "user_id": "442033704156",
                    "zoom_userid": "Unknown Speaker",
                    "client_type": 0,
                },
            ],
        },
        {
            "text": "personal trainer to see Simon. Cinema.",
            "end_ts": "00:00:12.720",
            "ts": "00:00:08.900",
            "users": [
                {
                    "username": "442033704156",
                    "multiple_people": False,
                    "user_id": "442033704156",
                    "zoom_userid": "Unknown Speaker",
                    "client_type": 0,
                },
            ],
        },
        {
            "text": "Um, Yes, sure.",
            "end_ts": "00:00:14.919",
            "ts": "00:00:13.030",
            "users": [
                {
                    "username": "foo Asset Management UK Ltd",
                    "multiple_people": False,
                    "user_id": "85180477870493817096",
                    "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                    "client_type": 0,
                },
            ],
        },
    ],
}

mocked_list_users = [
    [
        {
            "id": "5emPcRCnSVuZycJzB6oBzQ",
            "first_name": "Alexis",
            "last_name": "Lefebvre",
            "email": "alexis.lefebvre@foo.com",
            "type": 2,
            "pmi": 4549870044,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Macro Strategies",
            "created_at": "2022-06-24T08:59:27Z",
            "last_login_time": "2022-09-27T13:39:37Z",
            "last_client_version": "5.11.1.6602(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "69gNxGIqQH631yrKUWnxLQ",
            "first_name": "Michel",
            "last_name": "Massoud",
            "email": "michel.massoud@foo.com",
            "type": 2,
            "pmi": 3031805769,
            "timezone": "Europe/London",
            "verified": 1,
            "created_at": "2021-10-20T13:53:16Z",
            "last_login_time": "2022-09-28T15:29:21Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "6p8kctGZTnOD8B13rGhvLg",
            "first_name": "Deepak",
            "last_name": "Verma",
            "email": "deepak.verma@foo.com",
            "type": 2,
            "pmi": 2883638693,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T10:55:09Z",
            "last_login_time": "2022-10-02T20:18:28Z",
            "last_client_version": "5.12.1.8902(android)",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "AvzcKLBDRsSZHcgxYXq1fQ",
            "first_name": "Simon",
            "last_name": "Poggioli",
            "email": "simon.poggioli@foo.com",
            "type": 2,
            "pmi": 3676641548,
            "timezone": "Europe/London",
            "verified": 1,
            "created_at": "2022-05-23T13:17:47Z",
            "last_login_time": "2022-09-15T13:23:01Z",
            "last_client_version": "5.8.4.1736(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "eScqSrDyRpW_Mq5GKa2MFg",
            "first_name": "Graham",
            "last_name": "Robinson",
            "email": "graham.robinson@foo.com",
            "type": 2,
            "pmi": 3753610441,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Marketing",
            "created_at": "2021-04-08T17:19:48Z",
            "last_login_time": "2022-10-02T13:31:39Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "pic_url": "https://foo.zoom.us/p/eScqSrDyRpW_Mq5GKa2MFg/697c0956-6af4-4914-b52c-5d63d10ca5d6-3821",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "FpSM3CZfQIG2b_PJvJxgCA",
            "first_name": "Isabella",
            "last_name": "McCoy",
            "email": "isabella.mccoy@foo.com",
            "type": 2,
            "pmi": 8134454566,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-03-23T14:18:44Z",
            "last_login_time": "2022-09-30T13:02:43Z",
            "last_client_version": "5.7.6.1056(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "FqKjNWquTXi5qfFIeQQCFA",
            "first_name": "Nicolas",
            "last_name": "Verle",
            "email": "nicolas.verle@foo.com",
            "type": 2,
            "pmi": 8970245817,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2021-12-17T13:47:25Z",
            "last_login_time": "2022-10-02T13:47:00Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "pic_url": "https://foo.zoom.us/p/FqKjNWquTXi5qfFIeQQCFA/9183330f-45f5-45bd-b702-2efaabe5b292-7598",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "Iuct2fxDQkWo0kcwfyUs9g",
            "first_name": "Olsi",
            "last_name": "Arapi",
            "email": "olsi.arapi@foo.com",
            "type": 2,
            "pmi": 3180799093,
            "timezone": "",
            "verified": 1,
            "created_at": "2022-07-20T14:54:11Z",
            "last_login_time": "2022-09-28T14:30:11Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "j5R--gEMRxCvwvSwx8orkA",
            "first_name": "Jessica",
            "last_name": "Freckleton",
            "email": "jessica.freckleton@foo.com",
            "type": 2,
            "pmi": 2105533618,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T11:56:33Z",
            "last_login_time": "2022-09-28T10:00:19Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "mf6M4ZvJQPeiGYGZznulUw",
            "first_name": "Alexandra",
            "last_name": "Robbins",
            "email": "alexandra.robbins@foo.com",
            "type": 2,
            "pmi": 6429324446,
            "timezone": "",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T10:25:01Z",
            "last_login_time": "2022-09-27T07:11:39Z",
            "last_client_version": "5.11.1.6602(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "mHNxeZB7Req5yj7Jh01m8A",
            "first_name": "Christopher",
            "last_name": "Dokos Tzouros",
            "email": "christopher.dokostzouros@foo.com",
            "type": 2,
            "pmi": 4654775319,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-07-04T15:01:53Z",
            "last_login_time": "2022-09-29T15:44:55Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "nY2RhxowQ9CEDkdtyGx00w",
            "first_name": "Phil",
            "last_name": "Grayson",
            "email": "phil.grayson@foo.com",
            "type": 2,
            "pmi": 9171471542,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2022-05-23T10:25:56Z",
            "last_login_time": "2022-10-02T22:18:51Z",
            "last_client_version": "5.11.9.7938(android)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "O33CBnqiRK-H3sKBa40p1w",
            "first_name": "Dan",
            "last_name": "Wordsworth",
            "email": "foo@dna-av.co.uk",
            "type": 1,
            "pmi": 5326205319,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "",
            "created_at": "2021-10-29T17:15:48Z",
            "last_login_time": "2022-08-04T18:17:58Z",
            "last_client_version": "5.7.7.1105(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "o3cV5_poQ1axARka_Vae-w",
            "first_name": "Charles",
            "last_name": "Baz",
            "email": "charles.baz@foo.com",
            "type": 2,
            "pmi": 5919727561,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2021-10-25T09:55:40Z",
            "last_login_time": "2022-10-01T09:58:33Z",
            "last_client_version": "5.0.4301.0407(chromeos)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "ohsXGpVhS6-qZ7js6Mbd7w",
            "first_name": "Fehmi",
            "last_name": "Karagulla",
            "email": "fehmi.karagulla@foo.com",
            "type": 2,
            "pmi": 9191043326,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "",
            "created_at": "2020-03-02T13:46:20Z",
            "last_login_time": "2022-10-02T14:36:07Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "oQvxvFtvT2CMFm68iG7UPA",
            "first_name": "Jean-Baptiste",
            "last_name": "Hatt",
            "email": "jean-baptiste.hatt@foo.com",
            "type": 2,
            "pmi": 2229254075,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2022-05-23T10:26:07Z",
            "last_login_time": "2022-10-01T19:40:22Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "QCMTSUQBQHesnflm6p_I4A",
            "first_name": "Joseph",
            "last_name": "Gebran",
            "email": "joseph.gebran@foo.com",
            "type": 2,
            "pmi": 3125432155,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2020-07-28T07:30:30Z",
            "last_login_time": "2022-09-29T13:31:58Z",
            "last_client_version": "5.11.4.7185(win)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "rXLV90sYTNev-r47J8hnyw",
            "first_name": "Fingerprint",
            "last_name": "IP Sentinal",
            "email": "fingerprint@foo.com",
            "type": 1,
            "pmi": 2285224779,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Fingerprint",
            "created_at": "2022-06-10T14:06:17Z",
            "last_login_time": "2022-09-09T11:22:30Z",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "SbXrRGh6TlS24SnkvbLrCw",
            "first_name": "Ben",
            "last_name": "Sharp",
            "email": "ben.sharp@foo.com",
            "type": 2,
            "pmi": 5146432967,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T10:24:49Z",
            "last_login_time": "2022-06-28T11:24:54Z",
            "last_client_version": "5.10.4.5035(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "UKthU1hXTxezjhNZm0xv5g",
            "first_name": "Henry",
            "last_name": "Laing",
            "email": "henry.laing@foo.com",
            "type": 2,
            "pmi": 4204998538,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T11:59:48Z",
            "last_login_time": "2022-09-01T09:45:56Z",
            "last_client_version": "5.11.1.6602(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "uRymD7CTTu-7oWLCpUXnBg",
            "first_name": "Lindsay",
            "last_name": "Reid",
            "email": "lindsay.reid@foo.com",
            "type": 2,
            "pmi": 8863776100,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-05-23T12:54:27Z",
            "last_login_time": "2022-09-28T10:00:12Z",
            "last_client_version": "5.11.1.6602(win)",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "W-8HhiQJTzy4ZhVml5LxtA",
            "first_name": "keith",
            "last_name": "decarlucci",
            "email": "keith.decarlucci@foo.com",
            "type": 2,
            "pmi": 3996702209,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Macro Strategies",
            "created_at": "2021-09-01T12:45:16Z",
            "last_login_time": "2022-01-13T12:29:35Z",
            "last_client_version": "5.9.1.2160(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "W0v40vnzSjKhhhnlvpJpBw",
            "first_name": "James",
            "last_name": "Austin",
            "email": "james.austin@foo.com",
            "type": 2,
            "pmi": 8353807928,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "",
            "created_at": "2020-11-06T11:05:58Z",
            "last_login_time": "2022-09-22T06:19:53Z",
            "last_client_version": "5.11.1.6602(win)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "w7T_zz-kSOaDKTpqfqKLhA",
            "first_name": "Ghislain",
            "last_name": "Cortina",
            "email": "ghislain.cortina@foo.com",
            "type": 2,
            "pmi": 7369191759,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2021-07-14T11:42:04Z",
            "last_login_time": "2022-09-30T11:58:56Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "XD5VZiZVTMCrBnaw7Dw0iw",
            "first_name": "Liz",
            "last_name": "Newton",
            "email": "liz.newton@foo.com",
            "type": 2,
            "pmi": 2958931403,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2019-03-18T15:09:50Z",
            "last_login_time": "2022-10-02T10:32:07Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "pic_url": "https://foo.zoom.us/p/XD5VZiZVTMCrBnaw7Dw0iw/ec3cad41-2da8-4117-912d-4932730f2a9c-4946",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "0",
        },
        {
            "id": "xjGYJBulRKqrqecGgAbpqw",
            "first_name": "charmaine",
            "last_name": "Gooding",
            "email": "charmaine.gooding@foo.com",
            "type": 2,
            "pmi": 2534404355,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "",
            "created_at": "2022-08-04T15:24:12Z",
            "last_login_time": "2022-10-01T11:16:20Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "status": "active",
            "role_id": "1",
        },
        {
            "id": "Zf5WmbD-Ta21qliPoendNg",
            "first_name": "Can",
            "last_name": "Ozdemir",
            "email": "can.ozdemir@foo.com",
            "type": 2,
            "pmi": 2488655930,
            "timezone": "Europe/London",
            "verified": 1,
            "dept": "Investment Management",
            "created_at": "2020-10-29T08:36:29Z",
            "last_login_time": "2022-09-29T14:35:06Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
        {
            "id": "Zmhw6HHBSeOTM4iWF_jjbg",
            "first_name": "Steve",
            "last_name": "Platts",
            "email": "steve.platts@foo.com",
            "type": 2,
            "pmi": 3760066993,
            "timezone": "",
            "verified": 1,
            "dept": "Business Management",
            "created_at": "2022-06-24T14:18:56Z",
            "last_login_time": "2022-09-23T10:53:24Z",
            "last_client_version": "5.11.10.4478(iphone)",
            "language": "en-US",
            "phone_number": "",
            "status": "active",
            "role_id": "2",
        },
    ],
    {
        "alexis.lefebvre@foo.com": "5emPcRCnSVuZycJzB6oBzQ",
        "michel.massoud@foo.com": "69gNxGIqQH631yrKUWnxLQ",
        "deepak.verma@foo.com": "6p8kctGZTnOD8B13rGhvLg",
        "simon.poggioli@foo.com": "AvzcKLBDRsSZHcgxYXq1fQ",
        "graham.robinson@foo.com": "eScqSrDyRpW_Mq5GKa2MFg",
        "isabella.mccoy@foo.com": "FpSM3CZfQIG2b_PJvJxgCA",
        "nicolas.verle@foo.com": "FqKjNWquTXi5qfFIeQQCFA",
        "olsi.arapi@foo.com": "Iuct2fxDQkWo0kcwfyUs9g",
        "jessica.freckleton@foo.com": "j5R--gEMRxCvwvSwx8orkA",
        "alexandra.robbins@foo.com": "mf6M4ZvJQPeiGYGZznulUw",
        "christopher.dokostzouros@foo.com": "mHNxeZB7Req5yj7Jh01m8A",
        "phil.grayson@foo.com": "nY2RhxowQ9CEDkdtyGx00w",
        "foo@dna-av.co.uk": "O33CBnqiRK-H3sKBa40p1w",
        "charles.baz@foo.com": "o3cV5_poQ1axARka_Vae-w",
        "fehmi.karagulla@foo.com": "ohsXGpVhS6-qZ7js6Mbd7w",
        "jean-baptiste.hatt@foo.com": "oQvxvFtvT2CMFm68iG7UPA",
        "joseph.gebran@foo.com": "QCMTSUQBQHesnflm6p_I4A",
        "fingerprint@foo.com": "rXLV90sYTNev-r47J8hnyw",
        "ben.sharp@foo.com": "SbXrRGh6TlS24SnkvbLrCw",
        "henry.laing@foo.com": "UKthU1hXTxezjhNZm0xv5g",
        "lindsay.reid@foo.com": "uRymD7CTTu-7oWLCpUXnBg",
        "keith.decarlucci@foo.com": "W-8HhiQJTzy4ZhVml5LxtA",
        "james.austin@foo.com": "W0v40vnzSjKhhhnlvpJpBw",
        "ghislain.cortina@foo.com": "w7T_zz-kSOaDKTpqfqKLhA",
        "liz.newton@foo.com": "XD5VZiZVTMCrBnaw7Dw0iw",
        "charmaine.gooding@foo.com": "xjGYJBulRKqrqecGgAbpqw",
        "can.ozdemir@foo.com": "Zf5WmbD-Ta21qliPoendNg",
        "steve.platts@foo.com": "Zmhw6HHBSeOTM4iWF_jjbg",
    },
]

mocked_list_meetings_recordings_empty = {}
mocked_list_meetings_recordings = [
    [],
    [],
    [],
    [],
    [
        {
            "uuid": "FdDrPOtxSciBqYBeqkFvkQ==",
            "id": 87025065483,
            "account_id": "aNg6vhlFR3qQKhquq1NO7Q",
            "host_id": "eScqSrDyRpW_Mq5GKa2MFg",
            "topic": "Layton Road <> Melqart",
            "type": 2,
            "start_time": "2022-09-16T13:59:25Z",
            "timezone": "Europe/London",
            "duration": 32,
            "total_size": 31663878,
            "recording_count": 3,
            "share_url": "https://melqart.zoom.us/rec/share/lVXgTYzqK3NG_W2G5T2EFuhnPmFe5hViIxzBkJCMZRZSGdFm8hQ4pGI60jBshAMz.tQJH6tmguHVZUgtB",
            "recording_files": [
                {
                    "id": "9f5e8675-f064-4fc7-98b8-e019019dce72",
                    "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
                    "recording_start": "2022-09-16T13:59:26Z",
                    "recording_end": "2022-09-16T14:32:07Z",
                    "file_type": "TRANSCRIPT",
                    "file_extension": "VTT",
                    "file_size": 31735,
                    "play_url": "https://melqart.zoom.us/rec/play/zPzWSHvcKI5OC4QjGlZrU3p-fwCmPdH6K4ZdnON1BFnJZNbHMiIQCQ76YPNUj56IpjU55YYY1pUDL5eJ.jS6UrPuTvGjJVqtc",
                    "download_url": "https://melqart.zoom.us/rec/download/zPzWSHvcKI5OC4QjGlZrU3p-fwCmPdH6K4ZdnON1BFnJZNbHMiIQCQ76YPNUj56IpjU55YYY1pUDL5eJ.jS6UrPuTvGjJVqtc",
                    "status": "completed",
                    "recording_type": "audio_transcript",
                },
                {
                    "id": "fb99e074-f912-416b-9cbd-a48a34485b9a",
                    "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
                    "recording_start": "2022-09-16T13:59:26Z",
                    "recording_end": "2022-09-16T14:32:07Z",
                    "file_type": "M4A",
                    "file_extension": "M4A",
                    "file_size": 31215223,
                    "play_url": "https://melqart.zoom.us/rec/play/Ji0z9OiwbfkL4oAvOV5c6DnoEfEssOYCtrgqD3nSm-jWZg3RVx4xdkOhJgl2gjDdsD3HtNQF-RDyBn8G.KwBu3CSBb5mgRnSi",
                    "download_url": "https://melqart.zoom.us/rec/download/Ji0z9OiwbfkL4oAvOV5c6DnoEfEssOYCtrgqD3nSm-jWZg3RVx4xdkOhJgl2gjDdsD3HtNQF-RDyBn8G.KwBu3CSBb5mgRnSi",
                    "status": "completed",
                    "recording_type": "audio_only",
                },
                {
                    "id": "c2a724cf-b301-42ed-881c-7e885dd8a002",
                    "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
                    "recording_start": "2022-09-16T13:59:26Z",
                    "recording_end": "2022-09-16T14:32:07Z",
                    "file_type": "TIMELINE",
                    "file_extension": "JSON",
                    "file_size": 416920,
                    "download_url": "https://melqart.zoom.us/rec/download/qU-6E3tzVEkwgRsxAcV01HQGD_EOfRcJwoGeVBVCywfyC91kkf9PQmHeC32vNVBY2W2S6-YwFT_qn9QR.J1LWb271G6mk6H_J",
                    "status": "completed",
                    "recording_type": "timeline",
                },
            ],
        },
    ],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [],
    [
        {
            "uuid": "wu4Zs0MBRYaLwzx3yCitSw==",
            "id": 81261751463,
            "account_id": "aNg6vhlFR3qQKhquq1NO7Q",
            "host_id": "XD5VZiZVTMCrBnaw7Dw0iw",
            "topic": "Catch Up Zoom Meeting: Connor Brown of Man FRM/Michel Massoud & Graham Robinson of Melqart Asset Management ",
            "type": 2,
            "start_time": "2022-09-16T08:59:31Z",
            "timezone": "Europe/London",
            "duration": 61,
            "total_size": 59084955,
            "recording_count": 3,
            "share_url": "https://melqart.zoom.us/rec/share/YIBMxrUVv-aaUEaquB-IBCwem-MqIkRtKPhC-u9ua56yY6QfJ7x0PPrQ4x3HDeYh.oAk7_IKMaYkUOis2",
            "recording_files": [
                {
                    "id": "2cec88ef-a857-4755-8102-a14f0634307c",
                    "meeting_id": "wu4Zs0MBRYaLwzx3yCitSw==",
                    "recording_start": "2022-09-16T08:59:31Z",
                    "recording_end": "2022-09-16T10:00:35Z",
                    "file_type": "TRANSCRIPT",
                    "file_extension": "VTT",
                    "file_size": 58111,
                    "play_url": "https://melqart.zoom.us/rec/play/2Ifb8a5YPDZwJCDjyGEaaiBPTyPi3m6hgP_azCSIkw75zjWgB43gBw5G_V2mRWP5uZNwVQ34-nBJ-70t.kS7pOYKaNHD-RZvO",
                    "download_url": "https://melqart.zoom.us/rec/download/2Ifb8a5YPDZwJCDjyGEaaiBPTyPi3m6hgP_azCSIkw75zjWgB43gBw5G_V2mRWP5uZNwVQ34-nBJ-70t.kS7pOYKaNHD-RZvO",
                    "status": "completed",
                    "recording_type": "audio_transcript",
                },
                {
                    "id": "91f5e77c-5a59-4363-8dce-8b3b03665e27",
                    "meeting_id": "wu4Zs0MBRYaLwzx3yCitSw==",
                    "recording_start": "2022-09-16T08:59:31Z",
                    "recording_end": "2022-09-16T10:00:35Z",
                    "file_type": "M4A",
                    "file_extension": "M4A",
                    "file_size": 58301770,
                    "play_url": "https://melqart.zoom.us/rec/play/FjZUl3viVpRFryXXc5_n3c_ypgMP_Fh6jJpuoMyfMf3dscM-pN86W4i9oAhXLTDKFFbrrKQqIAPG2gJQ.fU9fCkB9ZVvgLLsD",
                    "download_url": "https://melqart.zoom.us/rec/download/FjZUl3viVpRFryXXc5_n3c_ypgMP_Fh6jJpuoMyfMf3dscM-pN86W4i9oAhXLTDKFFbrrKQqIAPG2gJQ.fU9fCkB9ZVvgLLsD",
                    "status": "completed",
                    "recording_type": "audfio_only",
                },
                {
                    "id": "fd401794-41d2-4149-bbc0-4cf72cdbbb21",
                    "meeting_id": "wu4Zs0MBRYaLwzx3yCitSw==",
                    "recording_start": "2022-09-16T08:59:31Z",
                    "recording_end": "2022-09-16T10:00:35Z",
                    "file_type": "TIMELINE",
                    "file_extension": "JSON",
                    "file_size": 725074,
                    "download_url": "https://melqart.zoom.us/rec/download/29ov_pQ4ltjEccB8PYOhvjht59tlu-TbKJpMBqV05tKiafUV7HdbFw5R3GSV_rbT7uztxAmnsmZYR5I.oIdpR-W24wX0b6wW",
                    "status": "completed",
                    "recording_type": "timeline",
                },
            ],
        },
    ],
    [],
    [],
    [],
]

mocked_put_meet_object = {
    "cdr": {
        "source": {"source_id": 81261751463, "source_type": "meet"},
        "date_of_action": "2022-09-06 13:48:17",
        "origin_from": {
            "persona_id": "XD5VZiZVTMCrBnaw7Dw0iw",
            "persona_first_name": "Liz",
            "persona_second_name": "Newton",
            "persona_number": "",
            "persona_email": "liz.newton@melqart.com",
            "persona_department": "Business Management",
        },
        "destination_to": {},
        "participants": [
            {
                "id": "mHNxeZB7Req5yj7Jh01m8A",
                "name": "Christopher Dokos Tzouros",
                "user_email": "cd.ci@foo.com",
            },
            {
                "id": "uRymD7CTTu-7oWLCpUXnBg",
                "name": "Lindsay Reid",
                "user_email": "lindsay.reid@melqart.com",
            },
            {"id": "", "name": "SusannahTrump", "user_email": ""},
            {
                "id": "j5R--gEMRxCvwvSwx8orkA",
                "name": "Jessica Freckleton",
                "user_email": "jessica.freckleton@melqart.com",
            },
            {
                "id": "XD5VZiZVTMCrBnaw7Dw0iw",
                "name": "Melqart Asset Management (UK) Ltd",
                "user_email": "liz.newton@melqart.com",
            },
            {"id": "", "name": "Steve Platts", "user_email": ""},
            {"id": "", "name": "Steve Platts", "user_email": ""},
        ],
    },
    "transcript": {
        "type": "VTT",
        "source": {"source_id": 81261751463, "source_type": "meet"},
        "recording_id": "b7f9345f-f83a-4e5b-821f-b9d0cfb72da1",
        "start_time": "2022-09-06 13:48:19",
        "end_time": "2022-09-06 14:37:50",
        "content": "https://melqart.zoom.us/rec/download/sJBNeS-8DwyQsB9I5M3WvcB-lCof4Zm9MIhB6wzY_Za1AKWqLT_ZcL7zmLvzTtDMEJE6FPBAqVKZqf0V.IAbyqe-sTBgFbTN7",
    },
    "recording": {
        "source": {"source_id": 81261751463, "source_type": "meet"},
        "type": "M4A",
        "play_url": "https://melqart.zoom.us/rec/play/ED8ctRJDLyxfCuxnJ_zwAikwbSb_qGeU8EKTO0I6saYSA3srHqWk91P-f1qG4OsJyS3zRrbl0NeVpHwB.PePmDwE_KCOb4ab4",
        "recording_id": "719ec322-34dc-42f6-b84c-17c27afefcec",
        "download_url": "https://melqart.zoom.us/rec/download/ED8ctRJDLyxfCuxnJ_zwAikwbSb_qGeU8EKTO0I6saYSA3srHqWk91P-f1qG4OsJyS3zRrbl0NeVpHwB.PePmDwE_KCOb4ab4",
    },
}

mocked_put_call_object = {
    "cdr": {
        "source": {
            "source_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "source_type": "call",
        },
        "date_of_action": "2022-09-16 17:25:17",
        "origin_from": {
            "persona_id": "Unknown",
            "persona_first_name": "Unknown",
            "persona_second_name": "Unknown",
            "persona_number": "+442033704156",
            "persona_email": "Unknown",
            "persona_department": "Unknown",
        },
        "destination_to": {
            "persona_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "persona_first_name": "Liz",
            "persona_second_name": "Newton",
            "persona_number": "+442038264491",
            "persona_email": "liz.newton@melqart.com",
            "persona_department": "Business Management",
        },
        "participants": [],
    },
    "transcript": {
        "type": "zoom_transcript",
        "source": {
            "source_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "source_type": "call",
        },
        "recording_id": "cf27f361606d46d2be780367727636b0",
        "start_time": "2022-09-16 17:25:36",
        "end_time": "2022-09-16 17:25:53",
        "content": [
            {
                "text": "Bakery test management.",
                "end_ts": "00:00:02.679",
                "ts": "00:00:00.700",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "You have a good personal trainer to see Simon S. Lima,",
                "end_ts": "00:00:06.580",
                "ts": "00:00:03.230",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "personal trainer to see Simon. Cinema.",
                "end_ts": "00:00:12.720",
                "ts": "00:00:08.900",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "Um, Yes, sure.",
                "end_ts": "00:00:14.919",
                "ts": "00:00:13.030",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
        ],
    },
    "recording": {
        "source": {
            "source_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "source_type": "call",
        },
        "type": "mp3",
        "play_url": "https://file.zoom.us/file?jwt=eyJhbGciOiJIUzI1NiJ9.eyJoZGlnIjpmYWxzZSwiaWljIjoiYXcxIiwiZXhwIjoxNjY1Mzc2NjQzLCJpc3MiOiJjcm9zc2ZpbGUiLCJhdWQiOiJmaWxlIiwiZGlnIjoiN2Y2YWRiOTJlZTc4ZTllMmJhY2NjZmU0YWIyMmE2ZTZlZGYxODcwNGFmYjVlMWNlODQ0ZDc2MGJmNWRjOTA1MyIsIm9yaSI6InBieHdlYiIsImlhdCI6MTY2NTM3NDg0NH0.zmNjcymZs0b5OPLewH_y80dBlGC5D_It-oZ__8Mi9fY&path=zoomfs%3A%2F%2Fzoom-pbx%2Frecording%2F2022%2F9%2F16%2F23vOATmyRHmTaj4vhE2Usg%2FR_YTRIFsQjGIEoPiY2DmQw%2Fcf27f361-606d-46d2-be78-0367727636b0%2Fcall_recording_cf27f361-606d-46d2-be78-0367727636b0_20220916172536.mp3",
        "recording_id": "cf27f361606d46d2be780367727636b0",
        "download_url": "https://zoom.us/v2/phone/recording/download/B_sI1k1XQnmGxMi_uJeuZQ",
    },
}

mocked_enhanced_call_zoomdto = ZoomDTO(
    cdr=CDR(
        source=ZoomEntity(source_id="cf27f361-606d-46d2-be78-0367727636b0", source_type="call"),
        date_of_action="2022-09-16 17:25:17",
        origin_from=PersonaDetails(
            persona_id="Unknown",
            persona_first_name="Unknown",
            persona_second_name="Unknown",
            persona_number="+442033704156",
            persona_email="Unknown",
            persona_department="Unknown",
        ),
        destination_to=PersonaDetails(
            persona_id="cf27f361-606d-46d2-be78-0367727636b0",
            persona_first_name="Liz",
            persona_second_name="Newton",
            persona_number="+442038264491",
            persona_email="liz.newton@melqart.com",
            persona_department="Business Management",
        ),
        participants=[],
    ),
    transcript=Transcript(
        type="zoom_transcript",
        source=ZoomEntity(source_id="cf27f361-606d-46d2-be78-0367727636b0", source_type="call"),
        recording_id="cf27f361606d46d2be780367727636b0",
        start_time="2022-09-16 17:25:36",
        end_time="2022-09-16 17:25:53",
        content=[
            {
                "text": "Bakery test management.",
                "end_ts": "00:00:02.679",
                "ts": "00:00:00.700",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "You have a good personal trainer to see Simon S. Lima,",
                "end_ts": "00:00:06.580",
                "ts": "00:00:03.230",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "personal trainer to see Simon. Cinema.",
                "end_ts": "00:00:12.720",
                "ts": "00:00:08.900",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "Um, Yes, sure.",
                "end_ts": "00:00:14.919",
                "ts": "00:00:13.030",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
        ],
    ),
    recording=Recording(
        source=ZoomEntity(source_id="cf27f361-606d-46d2-be78-0367727636b0", source_type="call"),
        type="mp3",
        play_url="https://file.zoom.us/file?jwt=eyJhbGciOiJIUzI1NiJ9.eyJoZGlnIjpmYWxzZSwiaWljIjoiYXcxIiwiZXhwIjoxNjY1Mzc2NjQzLCJpc3MiOiJjcm9zc2ZpbGUiLCJhdWQiOiJmaWxlIiwiZGlnIjoiN2Y2YWRiOTJlZTc4ZTllMmJhY2NjZmU0YWIyMmE2ZTZlZGYxODcwNGFmYjVlMWNlODQ0ZDc2MGJmNWRjOTA1MyIsIm9yaSI6InBieHdlYiIsImlhdCI6MTY2NTM3NDg0NH0.zmNjcymZs0b5OPLewH_y80dBlGC5D_It-oZ__8Mi9fY&path=zoomfs%3A%2F%2Fzoom-pbx%2Frecording%2F2022%2F9%2F16%2F23vOATmyRHmTaj4vhE2Usg%2FR_YTRIFsQjGIEoPiY2DmQw%2Fcf27f361-606d-46d2-be78-0367727636b0%2Fcall_recording_cf27f361-606d-46d2-be78-0367727636b0_20220916172536.mp3",
        recording_id="cf27f361606d46d2be780367727636b0",
        download_url="processed.zoom/2022-10-11/audio_file_cf27f361-606d-46d2-be78-0367727636b0_1665549527274.mp3",
    ),
)

mocked_user_detail = {
    "id": "foo",
    "first_name": "Will",
    "last_name": "Newton",
    "email": "will.newton@mypy.com",
    "type": 2,
    "role_name": "Owner",
    "pmi": 2958931403,
    "use_pmi": False,
    "personal_meeting_url": "https://mypy.zoom.us/j/123",
    "timezone": "Europe/London",
    "verified": 1,
    "dept": "Business Management",
    "created_at": "2019-03-18T15:09:50Z",
    "last_login_time": "2022-10-13T07:48:22Z",
    "last_client_version": "5.11.10.4478(iphone)",
    "pic_url": "https://mypy.zoom.us/p/123/946",
    "cms_user_id": "",
    "jid": "123@xmpp.zoom.us",
    "group_ids": [],
    "im_group_ids": [],
    "account_id": "aNg6vhlFR3qQKhquq1NO7Q",
    "language": "en-US",
    "phone_country": "GB",
    "phone_number": "",
    "status": "active",
    "job_title": "Office Manager",
    "location": "London",
    "login_types": [
        100,
    ],
    "role_id": "0",
    "account_number": 112233,
    "cluster": "us02",
}

mocked_list_phone_recordings_cf27 = {
    "id": "cf27f361606d46d2be780367727636b0",
    "caller_number": "442033704156",
    "caller_number_type": 2,
    "caller_name": "442033704156",
    "callee_number": "800",
    "callee_number_type": 1,
    "callee_name": "Melqart Asset Management UK Ltd",
    "direction": "inbound",
    "duration": 17,
    "download_url": "https://zoom.us/v2/phone/recording/download/B_sI1k1XQnmGxMi_uJeuZQ",
    "file_url": "https://file.zoom.us/file?jwt=eyJhbGciOiJIUzI1NiJ9.eyJoZGlnIjpmYWxzZSwib3JpIjoicGJ4d2ViIiwiYXVkIjoiZmlsZSIsImRpZyI6IjdmNmFkYjkyZWU3OGU5ZTJiYWNjY2ZlNGFiMjJhNmU2ZWRmMTg3MDRhZmI1ZTFjZTg0NGQ3NjBiZjVkYzkwNTMiLCJleHAiOjE2NjU5MDE4NDgsImlhdCI6MTY2NTkwMDA0OSwiaWljIjoiYXcxIiwiaXNzIjoiY3Jvc3NmaWxlIn0.xq4GT17-Dr2XANURRkzbDdTaaO6SiXzRgcBa1pYi0yE&path=zoomfs%3A%2F%2Fzoom-pbx%2Frecording%2F2022%2F9%2F16%2F23vOATmyRHmTaj4vhE2Usg%2FR_YTRIFsQjGIEoPiY2DmQw%2Fcf27f361-606d-46d2-be78-0367727636b0%2Fcall_recording_cf27f361-606d-46d2-be78-0367727636b0_20220916172536.mp3",
    "date_time": "2022-09-16T17:25:36Z",
    "recording_type": "Automatic",
    "call_log_id": "cf27f361-606d-46d2-be78-0367727636b0",
    "call_id": "7144030050769469138",
    "owner": {
        "type": "user",
        "id": "XD5VZiZVTMCrBnaw7Dw0iw",
        "name": "Melqart Asset Management (UK) Ltd",
        "extension_number": 800,
    },
    "site": {},
    "end_time": "2022-09-16T17:25:54Z",
}

mocked_meeting_detail_8702 = {
    "uuid": "FdDrPOtxSciBqYBeqkFvkQ==",
    "id": 87025065483,
    "host_id": "eScqSrDyRpW_Mq5GKa2MFg",
    "type": 2,
    "topic": "Layton Road <> Melqart",
    "user_name": "Graham Robinson",
    "user_email": "graham.robinson@melqart.com",
    "start_time": "2022-09-16T13:59:25Z",
    "end_time": "2022-09-16T14:32:07Z",
    "duration": 33,
    "total_minutes": 129,
    "participants_count": 5,
    "dept": "Marketing",
    "source": "Zoom",
}

mocked_meeting_participants = {
    "page_count": 1,
    "page_size": 30,
    "total_records": 5,
    "next_page_token": "",
    "participants": [
        {
            "id": "",
            "name": "Anthony Lombardi",
            "user_email": "",
        },
        {
            "id": "FpSM3CZfQIG2b_PJvJxgCA",
            "name": "Isabella McCoy",
            "user_email": "isabella.mccoy@melqart.com",
        },
        {
            "id": "z70_uJljS36WVmsS_nvaLg",
            "name": "Tom Mahala Jr.",
            "user_email": "",
        },
        {
            "id": "YgvewLXdTbeMA0DMVY7FFw",
            "name": "Jim Campbell",
            "user_email": "",
        },
        {
            "id": "4qETpEVKTSeUCmuJjgkhZg",
            "name": "Tom Mahala",
            "user_email": "",
        },
    ],
}

mocked_list_meeting_recordings = {
    "uuid": "FdDrPOtxSciBqYBeqkFvkQ==",
    "id": 87025065483,
    "account_id": "aNg6vhlFR3qQKhquq1NO7Q",
    "host_id": "eScqSrDyRpW_Mq5GKa2MFg",
    "topic": "Layton Road <> Melqart",
    "type": 2,
    "start_time": "2022-09-16T13:59:25Z",
    "timezone": "Europe/London",
    "host_email": "graham.robinson@melqart.com",
    "duration": 32,
    "total_size": 31663878,
    "recording_count": 3,
    "share_url": "https://melqart.zoom.us/rec/share/V5rIyIwg7qDkpnVLO_KdP501ILYpqqAHBP9G0xByDS_VftmqNYwzPMXM3Kzm1Vmm.crAMexNPa55OiL_1",
    "recording_files": [
        {
            "id": "fb99e074-f912-416b-9cbd-a48a34485b9a",
            "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
            "recording_start": "2022-09-16T13:59:26Z",
            "recording_end": "2022-09-16T14:32:07Z",
            "file_type": "M4A",
            "file_extension": "M4A",
            "file_size": 31215223,
            "play_url": "https://melqart.zoom.us/rec/play/KSKrbxKvz6zkXpZAAxF6y-Kt9y37aJ_5TEqXjq-XdjF5VWJwb38P5ydhHlR9JA6FWIa391SlxOoJvnwH.Tw0jEpOkyxZulj99",
            "download_url": "https://melqart.zoom.us/rec/download/KSKrbxKvz6zkXpZAAxF6y-Kt9y37aJ_5TEqXjq-XdjF5VWJwb38P5ydhHlR9JA6FWIa391SlxOoJvnwH.Tw0jEpOkyxZulj99",
            "status": "completed",
            "recording_type": "audio_only",
        },
        {
            "id": "c2a724cf-b301-42ed-881c-7e885dd8a002",
            "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
            "recording_start": "2022-09-16T13:59:26Z",
            "recording_end": "2022-09-16T14:32:07Z",
            "file_type": "TIMELINE",
            "file_extension": "JSON",
            "file_size": 416920,
            "download_url": "https://melqart.zoom.us/rec/download/Il3mls1ZsuxDLTKB3v99cBiMgQ1dbNeFiQ3ykrgWOGaZfElvTRsFn_cOhvFzRsGQdjIyGu0iH-3zZnMc.rhdnupB8eyH8oNB8",
            "status": "completed",
            "recording_type": "timeline",
        },
        {
            "id": "9f5e8675-f064-4fc7-98b8-e019019dce72",
            "meeting_id": "FdDrPOtxSciBqYBeqkFvkQ==",
            "recording_start": "2022-09-16T13:59:26Z",
            "recording_end": "2022-09-16T14:32:07Z",
            "file_type": "TRANSCRIPT",
            "file_extension": "VTT",
            "file_size": 31735,
            "play_url": "https://melqart.zoom.us/rec/play/T-i1DBtjNkfrbh_M1AWJeg9Qg_flcwO4tqrzZa-3PpHaKbW-VWSI-rju2oE-4zmWcU55AcAiL5nNCeNn.uuG7tdKCeNkn02UU",
            "download_url": "https://melqart.zoom.us/rec/download/T-i1DBtjNkfrbh_M1AWJeg9Qg_flcwO4tqrzZa-3PpHaKbW-VWSI-rju2oE-4zmWcU55AcAiL5nNCeNn.uuG7tdKCeNkn02U",
            "status": "completed",
            "recording_type": "audio_transcript",
        },
    ],
    "password": "G$RX&MS3",
    "recording_play_passcode": "cDOAx1sHTvkCQh22yI7J__MaKnGUvcc4",
}

mocked_download_endpoint = bytes("mocked_binary_file".encode("utf-8"))

mocked_lambda_process_call_cf27 = {
    "cdr": {
        "source": {"source_id": "cf27f361-606d-46d2-be78-0367727636b0", "source_type": "call"},
        "date_of_action": "2022-09-16 17:25:17",
        "origin_from": {
            "persona_id": "Unknown",
            "persona_first_name": "Unknown",
            "persona_second_name": "Unknown",
            "persona_number": "+442033704156",
            "persona_email": "Unknown",
            "persona_department": "Unknown",
        },
        "destination_to": {
            "persona_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "persona_first_name": "Liz",
            "persona_second_name": "Newton",
            "persona_number": "+442038264491",
            "persona_email": "liz.newton@melqart.com",
            "persona_department": "Business Management",
        },
        "participants": [],
    },
    "transcript": {
        "type": "zoom_transcript",
        "source": {
            "source_id": "cf27f361-606d-46d2-be78-0367727636b0",
            "source_type": "call",
        },
        "recording_id": "cf27f361606d46d2be780367727636b0",
        "start_time": "2022-09-16 17:25:36",
        "end_time": "2022-09-16 17:25:53",
        "content": [
            {
                "text": "Bakery test management.",
                "end_ts": "00:00:02.679",
                "ts": "00:00:00.700",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "You have a good personal trainer to see Simon S. Lima,",
                "end_ts": "00:00:06.580",
                "ts": "00:00:03.230",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "personal trainer to see Simon. Cinema.",
                "end_ts": "00:00:12.720",
                "ts": "00:00:08.900",
                "users": [
                    {
                        "username": "442033704156",
                        "multiple_people": False,
                        "user_id": "442033704156",
                        "zoom_userid": "Unknown Speaker",
                        "client_type": 0,
                    },
                ],
            },
            {
                "text": "Um, Yes, sure.",
                "end_ts": "00:00:14.919",
                "ts": "00:00:13.030",
                "users": [
                    {
                        "username": "foo Asset Management UK Ltd",
                        "multiple_people": False,
                        "user_id": "85180477870493817096",
                        "zoom_userid": "XD5VZiZVTMCrBnaw7Dw0iw",
                        "client_type": 0,
                    },
                ],
            },
        ],
    },
    "recording": {
        "source": {"source_id": "cf27f361-606d-46d2-be78-0367727636b0", "source_type": "call"},
        "type": "mp3",
        "play_url": "https://file.zoom.us/file?jwt=eyJhbGciOiJIUzI1NiJ9.eyJoZGlnIjpmYWxzZSwiaWljIjoiYXcxIiwiZXhwIjoxNjY1Mzc2NjQzLCJpc3MiOiJjcm9zc2ZpbGUiLCJhdWQiOiJmaWxlIiwiZGlnIjoiN2Y2YWRiOTJlZTc4ZTllMmJhY2NjZmU0YWIyMmE2ZTZlZGYxODcwNGFmYjVlMWNlODQ0ZDc2MGJmNWRjOTA1MyIsIm9yaSI6InBieHdlYiIsImlhdCI6MTY2NTM3NDg0NH0.zmNjcymZs0b5OPLewH_y80dBlGC5D_It-oZ__8Mi9fY&path=zoomfs%3A%2F%2Fzoom-pbx%2Frecording%2F2022%2F9%2F16%2F23vOATmyRHmTaj4vhE2Usg%2FR_YTRIFsQjGIEoPiY2DmQw%2Fcf27f361-606d-46d2-be78-0367727636b0%2Fcall_recording_cf27f361-606d-46d2-be78-0367727636b0_20220916172536.mp3",
        "recording_id": "cf27f361606d46d2be780367727636b0",
        "download_url": "processed.zoom/2022-10-16/audio_file_cf27f361-606d-46d2-be78-0367727636b0_1665977249398.mp3",
    },
}
