name: Deploy Lambda Docker Functions to AWS

on:
  push:
    branches:
      - docker-state-machine
      - main
    paths:
      - .github/workflows/**
      - docker_ingest/**
env:
  ENV_NAME: dev
  PYTHON_VERSION: 3.8
  NODE_VERSION: 18.x
  REGION_KEY: EU_WEST_1

jobs:
  deploy:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./docker_ingest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-node@v3
        with:
          node-version: ${{ env.NODE_VERSION }}
          cache: 'npm'

      - name: Setup Python ${{ env.PYTHON_VERSION }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Install serverless
        run: npm install -g serverless

      - name: Install npm dependencies
        run: npm ci --python=${{ env.pythonLocation }}

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets[format('AWS_ACCESS_KEY_ID_{0}_{1}', env.ENV_NAME, env.REGION_KEY)] }}
          aws-secret-access-key: ${{ secrets[format('AWS_SECRET_ACCESS_KEY_{0}_{1}', env.ENV_NAME, env.REGION_KEY)] }}
          aws-region: eu-west-1

      - run: |
          npx sls deploy -s ${{ env.ENV_NAME }}
